# Generated by Django 2.1.3 on 2018-11-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagen', models.ImageField(upload_to='upload')),
                ('NombreMascota', models.CharField(max_length=20)),
                ('RazaPredominante', models.CharField(max_length=15)),
                ('Descripcion', models.TextField()),
                ('Estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Rescatado', 'Rescatado'), ('Adoptado', 'Adoptado')], default='Disponible', max_length=10)),
                ('FechaPublicado', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
